import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import { GlobalProvider } from "./context/globalContext";

export const metadata: Metadata = {
  title: "Pass The Time",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="dark:from-light dark:to-light text-dark bg-gradient-to-r from-secondary to-accent-secondary dark:bg-gradient-to-b overflow-y-hidden h-full">
        <GlobalProvider>
          <Navbar />

          {/* dark mode cursor spotlight */}
          <div id="spotlight" className="hidden dark:block"></div>

          {/* lightbox overlay */}
          <div
            id="overlay"
            style={{ opacity: 0 }}
            className="h-screen w-screen bg-dark absolute z-10 hidden"
          ></div>

          <main role="main" className="h-full">
            {children}
          </main>
        </GlobalProvider>
      </body>
    </html>
  );
}
